# Generated by Django 3.0.5 on 2020-04-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_data',
            field=models.TextField(),
        ),
    ]
